### ISSUE TITLE
Maven test with error

### ISSUE THREAD

**Issue by pedroxs** [patka/cassandra-migration#1]
I tried running the maven tests but keep getting this error:

`DatabaseTest.shouldApplyMigrationToDatabaseWhenMigrationsAndEmptyDatabaseGiven:47 » NoHostAvailable`

Full exception: 

`FAILURE! - in org.cognitor.cassandra.it.migration.DatabaseTest
shouldApplyMigrationToDatabaseWhenMigrationsAndEmptyDatabaseGiven(org.cognitor.cassandra.it.migration.DatabaseTest)  Time elapsed: 14.179 sec  <<< ERROR!
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)
	at org.cognitor.cassandra.it.migration.DatabaseTest.shouldApplyMigrationToDatabaseWhenMigrationsAndEmptyDatabaseGiven(DatabaseTest.java:47)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)
	at org.cognitor.cassandra.it.migration.DatabaseTest.shouldApplyMigrationToDatabaseWhenMigrationsAndEmptyDatabaseGiven(DatabaseTest.java:47)
`

I also get this warning a lot:

`WARN  Cluster:2105 - You listed localhost/0:0:0:0:0:0:0:1:9142 in your contact points, but it wasn't found in the control host's system.peers at startup`

And also lots of infos like this one:

`INFO  Cluster:1475 - New Cassandra host localhost/127.0.0.1:9142 added`

Apparently the tests are running ok but something is breaking at some point, I have not used CassandraUnit before and was wondering if you could give a helping hand.

If you need more details just ask.

**Comment by patka** [comment]
Hi Joaquim,

I have the same problem currently but strangly not on all machines. On my Linux box this is working while it is failing on my Macbook. I will need to take a closer look on this and I will come back to you as soon as I have some news on this.

Cheers
Patrick

**Comment by patka** [comment]
I just committed a fix. Can you please check if it is now working for you? Turns out the test was failing for a reason. Sorry for this inconvinience. I will also see if I can fix this noise from CassandraUnit.

Cheers

**Comment by pedroxs** [comment]
Thanks Patrick, everything fine now!

**Comment by KalavaraSiri** [comment]
facing in the same issue with TEST 

mvnw -Pprod package

All host(s) tried for query failed (tried: /127.0.0.1:4092 (com.datastax.driver.core.exceptions.TransportException: [/
127.0.0.1] Cannot connect))

**Comment by patka** [comment]
Hi, may I ask which version you are using and is this an error that you receive locally or within a CI system like Jenkins or Travis-CI?

Since you are building it yourself I assume you use the latest snapshot?
