### ISSUE TITLE
Baseline

### ISSUE THREAD

**Issue by kevinmic** [patka/cassandra-migration#10]
Is there a way to baseline to a given version?

**Comment by patka** [comment]
Can you elaborate a little bit more what you mean by "baseline"?

Cheers
Patrick

**Comment by kevinmic** [comment]
Something like this -- https://flywaydb.org/documentation/command/baseline

Essentially it allows you to skip to a certain migration number.   This allows you to create a "base" version of your entire database.   Then you baseline your migrations so that migrations run after that point.
