### ISSUE TITLE
Customized Scanner Factory

### ISSUE THREAD

**Issue by kevinmic** [patka/cassandra-migration#13]
In my application I have run across an issue loading the cql files.   I am using jboss and a .war file and unfortunately jboss is doing some magic that prevents the java.nio.FileSystem directory scanning from working correctly.    I would like to override the scannerFactory in the MigrationFactory to get around this problem.

Thoughts?  How would you go about changing the api to allow for this?

**Comment by patka** [comment]
Hi Kevin,

I will come back to you regarding this topic and the other items. But I am in vacation now for two weeks and I don't think that I will have much time to work on these topic. But be assured, after this we can discuss the issues.

Cheers
Patrick

**Comment by kevinmic** [comment]
Any thoughts on this?

**Comment by patka** [comment]
Hi Kevin,

I think it should not be a big issue to make the library more open here. In fact, it seems very reasonable. I will start working on it asap.

Cheers
Patrick

**Comment by patka** [comment]
Hi Kevin,

I am investigating the idea of going into the direction that I will change the ScannerFactory to be some sort of registry where you can register scanners for different kind of schemes. That makes it a little bit more open and does not require you to overwrite library components. Would that be a solution for you?

Cheers
Patrick

**Comment by kevinmic** [comment]
That would work great, thanks!
