### ISSUE TITLE
error during migration of Functions

### ISSUE THREAD

**Issue by shaynechmad** [patka/cassandra-migration#15]
I tried to migrate the function :
CREATE OR REPLACE FUNCTION avgState ( state tuple<int,double>, val float ) CALLED ON NULL INPUT RETURNS tuple<int,double> LANGUAGE java AS 'if (val !=null) { state.setInt(0, state.getInt(0)+1); state.setDouble(1, state.getDouble(1) + val.doubleValue()); } return state;'; 

and because of the STATEMENT_DELIMITER = ";" the query was cutted in the middle.

**Comment by patka** [comment]
Ha, nice one ;-) I must admin that I did not have functions in mind when I created the library...
I will dig into this and see if there is a better solution that will work with your code. I just cannot make any promises for the timeframe right now.

Cheers
Patrick

**Comment by shaynechmad** [comment]
Hi Patrick,

I'm using Cassandra-unit for testing, and I found a code that deal with this issue, see license [https://github.com/jsevellec/cassandra-unit/blob/master/LICENSE.txt](url)

I extracted the parser code and joined it to one class. see attached java file
[SimpleCQLLexer.txt](https://github.com/patka/cassandra-migration/files/1352390/SimpleCQLLexer.txt)


Thanks,
Shay

**Comment by patka** [comment]
Hi Shay,

thanks a lot for doing the research. Sorry, my time is currently quite limited as we are expecting the second child at home.
I actually did start yesterday to look into using ANTLR and using the grammars that are inside the Apache Cassandra server package. Now, what you found looks even better as it does not require any additional depenencies. I will see that I get it integrated ASAP and make a release with the fix of the other issue as well.

Cheers
Patrick

**Comment by patka** [comment]
Hi Shay,

v2.1.1 is released and contains the fix. If something is still wrong let me know.

Cheers
Patrick

**Comment by shaynechmad** [comment]
Hi Patrick,

Sorry for the late reply, I was on vacation.
Congratulation for the new baby!

I've downloaded your latest version and it works fine. However I require additional feature - checksum support. I'd be happy to send you a sample code for this support if you prefer so (I'm sure your hands are full). I'll send you a new message with more details of checksum support.

Thanks,
Shay
