### ISSUE TITLE
Spring boot fat jar location scanning not working with default path

### ISSUE THREAD

**Issue by Glamdring** [patka/cassandra-migration#18]
In a fat spring boot jar I get a failure:

Caused by: java.nio.file.NoSuchFileException: cassandra/migration
        at jdk.zipfs/jdk.nio.zipfs.ZipPath.getAttributes(Unknown Source)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.readAttributes(Unknown Source)
        at java.base/java.nio.file.Files.readAttributes(Unknown Source)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(Unknown Source)
        at java.base/java.nio.file.FileTreeWalker.visit(Unknown Source)
        at java.base/java.nio.file.FileTreeWalker.walk(Unknown Source)
        at java.base/java.nio.file.FileTreeIterator.<init>(Unknown Source)
        at java.base/java.nio.file.Files.walk(Unknown Source)
        at java.base/java.nio.file.Files.walk(Unknown Source)
        at org.cognitor.cassandra.migration.scanner.JarLocationScanner.findResourceNames(JarLocationScanner.java:34)
        at org.cognitor.cassandra.migration.MigrationRepository.scanForScripts(MigrationRepository.java:181)
        at org.cognitor.cassandra.migration.MigrationRepository.<init>(MigrationRepository.java:131)

This is probably because the jar has a specific structure: BOOT-INF/classes/cassandra/migration

To address that, maybe introduce multiple values for the script path properties - one that works in a fat-jar context, and another one that works in a regular "Run application" context

**Comment by patka** [comment]
Hi,

you are right. That is not the way it is supposed to be. Would it be possible for you to provide me a minimal test or usage example that reproduces the issue so that I can look into it and have the possibility to check if the issue is fixed?

Thanks
Patrick

**Comment by Glamdring** [comment]
The important part of the pom I think is this:

			```
<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>org.springframework</groupId>
						<artifactId>springloaded</artifactId>
						<version>1.2.6.RELEASE</version>
					</dependency>
				</dependencies>
				<configuration>
					<executable>true</executable>
				</configuration>
			</plugin>
```

It creates an executable jar which brings the BOOT-INF structure: BOOT-INF/classes/cassandra/migration

I think supplying multiple paths instead of just one would resolve the issue.

**Comment by patka** [comment]
I find it strange that it does not find it since the repository is looking in the classpath and I would have assumed that even if the classes are in BOOT-INF/classes that Spring constructs the classpath accordingly so that everything works as expected. I would like to have a closer look at this as I really hope to find a better solution than having a library that needs to know where it is used. This sounds wrong to me ;-)

**Comment by Glamdring** [comment]
It finds stuff on the classpath, but scanning is done using the Jar...scanner, which in facts opens the zip (jar) file and looks inside it. That's where it breaks.

I agree with your comment, though - this is why my suggestion of supporting multiple locations is okay, I think. By default it will have just the default location of classpath:/cassandra/migration. In the spring-boot project you can add the second value. Thus only the spring-boot project will add spring-boot specifics, which is fine

**Comment by backjo** [comment]
We implemented a pretty basic spring boot location scanner to get around this:
```java
import org.cognitor.cassandra.migration.scanner.LocationScanner;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

import java.io.IOException;
import java.net.URI;
import java.util.HashSet;
import java.util.Set;

public class SpringBootLocationScanner implements LocationScanner {
    private PathMatchingResourcePatternResolver resourcePatternResolver = new PathMatchingResourcePatternResolver();

    @Override
    public Set<String> findResourceNames(String location, URI locationUri) throws IOException {
        Resource[] resources = resourcePatternResolver.getResources(location + "*.cql");

        Set<String> resourcePaths = new HashSet<>();
        for(int i=0; i<resources.length; i++) {
            resourcePaths.add(location + resources[i].getFilename());
        }
        return resourcePaths;
    }
}
`

**Comment by turbospaces** [comment]
any updates on issue? i just faced it too

**Comment by patka** [comment]
I am trying to figure out a way to know inside the location scanner if I am inside a spring boot fat jar. Sorry, for all the delays. Family issues. I will get back to you.

**Comment by patka** [comment]
I included the code of @backjo in the cassandra-migration-spring-boot-starter. If you use this module it should work out of the box. 
Let me know if there are any issues. I just released the new version, so it can take up to 24 hours until it is available in the maven repositories.

**Comment by dnsbtchr** [comment]
Because I needed it to work with either a normal Jar or a Spring Boot Jar, I ended up with this composite version of the LocationScanner:
```java
/**
 * Composite {@link JarLocationScanner} which first tries to lookup the resource names using {@link
 * SpringBootLocationScanner} and then using {@link JarLocationScanner}. This is needed because in both cases Jar files
 * and used for the resources but the packaging is different and each on will not find anything for the other type.
 * Since there is no way to distinguish between a normal Jar and a Spring Boot Jar easily, this seems to be the easiest
 * way of handling that.
 */
@Slf4j
@AllArgsConstructor(access = AccessLevel.PACKAGE)
class CompositeLocationScanner implements LocationScanner {

  private final JarLocationScanner jarLocationScanner;

  private final SpringBootLocationScanner springBootLocationScanner;

  CompositeLocationScanner() {
    jarLocationScanner = new JarLocationScanner();
    springBootLocationScanner = new SpringBootLocationScanner();
  }

  @Override
  public Set<String> findResourceNames(String location, URI locationUri) throws IOException {
    Set<IOException> thrownExceptions = new HashSet<>();
    try {
      return springBootLocationScanner.findResourceNames(location, locationUri);
    } catch (IOException e) {
      thrownExceptions.add(e);
    }

    try {
      return jarLocationScanner.findResourceNames(location, locationUri);
    } catch (IOException e) {
      thrownExceptions.add(e);
    }

    thrownExceptions.forEach(e -> log.error("Could not find resources names", e));
    throw new IOException("Scanning using SpringBootLocationScanner and JarLocationScanner failed");
  }
}
```

**Comment by danitochilin** [comment]
I have overridden the SpringBootLocationScanner class, to make it work with the spring boot version 2.5.1

`package org.cognitor.cassandra.migration.spring.scanner;

import java.io.IOException;
import java.net.URI;
import java.util.HashSet;
import java.util.Set;
import lombok.extern.slf4j.Slf4j;
import org.cognitor.cassandra.migration.scanner.LocationScanner;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

@Slf4j
public class SpringBootLocationScanner implements LocationScanner {

  private final PathMatchingResourcePatternResolver resourcePatternResolver = new PathMatchingResourcePatternResolver();

  @Override
  public Set<String> findResourceNames(final String location, final URI locationUri) throws IOException {

    final Resource[] resources = getResources(location);

    log.debug("Resources: {}", resources.length);

    final Set<String> resourcePaths = new HashSet<>();
    for (final Resource resource : resources) {
      resourcePaths.add(resource.getURI()
          .toString());
    }
    return resourcePaths;
  }

  private Resource[] getResources(final String location) throws IOException {

    final String locationPattern = "classpath:" + location + "*.cql";
    log.debug("Get resources from location pattern {}", locationPattern);
    final Resource[] resources = resourcePatternResolver.getResources(locationPattern);

    if (resources.length == 0) {
      final String locationPatternAllFolders = "classpath:" + location + "**/*.cql";
      log.debug("Get resources from location pattern all folders {}", locationPatternAllFolders);
      return resourcePatternResolver.getResources(locationPatternAllFolders);
    }

    return resources;
  }
}
`
