### ISSUE TITLE
README.md file: artifactId for SpringBoot dependency is not correct

### ISSUE THREAD

**Issue by ganov** [patka/cassandra-migration#22]
Actual version:
\<dependency>
      \<groupId>org.cognitor.cassandra\</groupId>
      \<artifactId>cassandra-migration-spring-boot-**stater**\</artifactId>
      \<version>2.1.0\</version>
\</dependency>

good one:
\<dependency>
      \<groupId>org.cognitor.cassandra\</groupId>
      \<artifactId>cassandra-migration-spring-boot-**starter**\</artifactId>
      \<version>2.1.1\</version>
\</dependency>

**Comment by ganov** [comment]
#23

**Comment by patka** [comment]
I merged your request. Thanks for fixing this.

**Comment by ganov** [comment]
My pleasure!!
Thx for your work !
