### ISSUE TITLE
Schema modifications are made incorrectly...

### ISSUE THREAD

**Issue by alexott** [patka/cassandra-migration#36]
README describes that modifications are done by using `QUORUM`:

> Migrations are executed with the Quorum consistency level to make sure that always a majority of nodes share the same schema information.

but it's incorrect - the schema changes are performed via different path than other operations, like, `INSERT`, etc.  See https://stackoverflow.com/questions/41248615/set-consistency-level-for-cassandra-ddl for more information 

to perform correct schema modifications you need to wait for schema agreement explicitly, see [java driver doc](https://docs.datastax.com/en/developer/java-driver/3.6/manual/metadata/#schema-agreement), and this [example](https://github.com/alexott/dse-java-playground/blob/master/src/main/java/com/datastax/alexott/demos/jdtest1/WhiteListPolicyExample.java#L40).

**Comment by patka** [comment]
Hi

yes, you are right. Thanks for the hint. I will adapt the code accordingly.

Thanks!

**Comment by patka** [comment]
It took a while but I released an updated version 2.2.1 that includes a fix for this. I will close this issue now. If there are any problems feel free to reopen it.

Cheers
Patrick
