### ISSUE TITLE
Duplicate script versions

### ISSUE THREAD

**Issue by jakobnordztrom** [patka/cassandra-migration#5]
Hi Patrick,

Currently scripts with duplicate versions are silently ignored.  What do you think of a change that would force the migration to fail when there are duplicate version in the migration directory?  We could keep current behaviour as the default and switch on the 'force failure on duplicate versions' functionality via a flag.  The reason for this change is that I'm evaluating your lib for a fairly large project with many committers and I want them to get feedback on build issues asap.

Regards,
Jakob

**Comment by patka** [comment]
Hi Jakob,

sorry it took me so long to look into your pull request but unfortunately I was sick the whole week.

This sounds like a good idea to fail fast in case of duplicate scripts. I suggest that in such a case  the migration is not even started but an exception is thrown immediately. This should not take too much time to implement. 

I will look into it.

Cheers
Patrick

**Comment by patka** [comment]
Hi Jakob,

sorry that it took me so long. I implemented your request and made it the new default behavior. I introduced a new interface that can be used to modify the behavior of the repository when it comes to the scanning process for scripts. I preferred this over a flag as it leaves the possibility open to implement other behaviors without introducing yet another flag.

Please let me know if this solution works for you.

Cheers
Patrick

**Comment by patka** [comment]
Since there was no answer I consider this as a "yes" and it will be included like this in the next release.
