### ISSUE TITLE
2.5.0_v4 not available from maven

### ISSUE THREAD

**Issue by ikstewa** [patka/cassandra-migration#64]
Hey @patka! I saw you released 2.5.0_v4 with the latest execution profile updates. I'm not seeing this version available from maven. Could you publish the new version? Thanks!

https://mvnrepository.com/artifact/org.cognitor.cassandra/cassandra-migration

**Comment by patka** [comment]
that is strange because I am pretty sure I published it. I will have a look later today.

**Comment by patka** [comment]
It's on its way now. Give it some time to be distributed in the maven repos. I forgot one step, closed the staging repo but did not release it. Sorry for the inconvenience.

**Comment by ikstewa** [comment]
Confirmed I'm now able to pull 2.5.0_v4 from maven. Thank you!
