### ISSUE TITLE
To be able to create keyspace as part of the migration file ?

### ISSUE THREAD

**Issue by mariogarcia** [patka/cassandra-migration#8]
First of all, nice work :+1: 

My use case is that I would like to be able to create the keyspace as the first statement of my migrations, and the library assumes that the keyspace is already created prior to apply the migrations.

```groovy
Database databaseConnection = new Database(cluster, 'mykeyspace')
MigrationTask migrationTask = new MigrationTask(
    databaseConnection, 
    new MigrationRepository())

migrationTask.migrate()
```

For instance, if I wanted to do integration tests, I would like not to create the keyspace by hand before running the migrations, and add it as part of the migration file:

```sql
-- 001_migration.cql
CREATE KEYSPACE mykeyspace
       WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 2 };
```
Is this something feasible ?

**Comment by mariogarcia** [comment]
As a workaround, I'm using the `cluster` instance to create the keyspace before executing migrations

```groovy

// CREATE KEYSPACE
static final String CREATE_KEYSPACE = """
  CREATE KEYSPACE mykeyspace
    WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };
"""

cluster.connect().execute(CREATE_KEYSPACE)

// APPLY MIGRATIONS
Database databaseConnection = new Database(cluster, 'mykeyspace')
MigrationTask migrationTask = new MigrationTask(
    databaseConnection, 
    new MigrationRepository())

migrationTask.migrate()
```

**Comment by patka** [comment]
Hi Mario,

I think this is feasible. I will have a look into it within the next days and come back to you. On the weekend, I am afraid, I am busy and won't have time for it.

Just one question: Do you setup the keyspace once in your tests or do you create it for each test and drop it afterwards?

Cheers
Patrick

**Comment by mariogarcia** [comment]
Well I haven't done it yet. To me there're two options:

- Due the fact that Cassandra doesn't do rollbacks, **if I run the migration once before all tests**
  - I'm forced to remove data produced by each test. 
  - It will be **_faster_**...
  - ...but it also could potentially lead to a **_single test producing a snowball problem_**.

- On the other hand **if I run the migrations before every test**
  - it will be _**slower**_
  - but it would be _**more consistent**_ 
  - and I think it would be _**less error prone**_.
  - ... and that usually means **easier to maintain**

I would go for the second option.

**Comment by patka** [comment]
OK, l am asking because it means that you need to be able to drop the keyspace after each test. I think I would start with the possibility to set a configuration parameter like "createKeyspaceIfMissing". Like this the keyspace would be created if it does not exist.

This can be done very easily. I will also check for the possibility to use the "USE <keyspace>" statement in the migration scripts but if I am not mistaken this statement needs to be performed as a query while all the others are performed as statements, so it would require that the library understands a little bit better what is inside the scripts.

**Comment by mariogarcia** [comment]
Mmmm I've got an idea:

Without chaning anything. Lets say I don't include the keyspace creation in the migration file, but it's part of the bootstrap mechanism.

When executing:

```groovy
Keyspace mainKeyspace = new Keyspace('keyspace', 3)
Database databaseConnection = new Database(cluster, keyspace)
MigrationTask migrationTask = new MigrationTask(
    databaseConnection, 
    new MigrationRepository())

migrationTask.migrate()
```
`Keyspace` could map the way you want to handle bootstrapping. It has the name of the keyspace, the replication factor. If you use the overloaded constructor of `Database` using the `Keyspace` object then you are telling the engine to create the keyspace with the required replication factor.

or maybe you can just have a flag indicating whether you want the engine to create the keyspace or not:

```groovy
Keyspace mainKeyspace = new Keyspace('keyspace', 3)
Database databaseConnection = new Database(cluster, keyspace, true)
MigrationTask migrationTask = new MigrationTask(
    databaseConnection, 
    new MigrationRepository())

migrationTask.migrate()
```

That also will help having a configuration file like this:

```yaml
migration:
  basedir: db/migrations
  keyspace:
    name: books
    create: true
```
Of course the creation of the keyspace must be the first entry in the migration table.

Thanks for taking the time to look into this :)

**Comment by patka** [comment]
Hi Mario,

no problem. I am always interested in ways to improve the library :)

I thought about a configuration object as well already. I guess, I will
implement the overloading constructor to have a solution for now, while
the configuration object will come with the next major release as the
change might not be completely backward compatible but in order to make
the API ready for easier extension it has to change in some places
unfortunately.

I will come back to you soon.

Cheers
Patrick

Am 27.06.17 um 08:57 schrieb Mario Garcia:

**Comment by mariogarcia** [comment]
Completely understandable Patrick :+1: 

Looking forward to hearing from you
Mario

**Comment by patka** [comment]
Hi Mario,

I just pushed a commit to the branch "keyspace_creation". Can you have a look and see if this would solve your problem regarding the keyspace creation? I am not yet clear on the naming but roughly this could be a solution.

There is a new constructor that takes a keyspace argument. With that object you can configure the name and the replication strategy. The Database object will then create a keyspace if it does not exists. It ensures this by putting the "IF NOT EXISTS" on the CREATE statement and also by checking the metadata of the cluster object if a keyspace by this name does not already exist.

Cheers
Patrick

**Comment by mariogarcia** [comment]
Awesome! I'm definitely taking a look to it during the week and let you know asap :)

**Comment by mariogarcia** [comment]
Hi Patrick:

I've checkout your changes, and it works like a charm. To me is a :+1: 

BTW: In the meantime I've found a bug. I'm adding the issue.

**Comment by patka** [comment]
Hi Mario,

that sounds good. I will see that I get a release done this week before I will go in vacation.

Cheers
Patrick

**Comment by mariogarcia** [comment]
That sounds great thanks!
